version: "2.4"

services:
  web:
    build: .
    image: web:latest
    volumes:
      - ./app:/build/app
    ports:
      - 8008:8000
    environment:
      - DATABASE_URL=postgresql://fastapi_traefik:fastapi_traefik@pg:5432/fastapi_traefik
    depends_on:
      pg:
        condition: service_healthy
  pg:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=fastapi_traefik
      - POSTGRES_PASSWORD=fastapi_traefik
      - POSTGRES_DB=fastapi_traefik
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U fastapi_traefik" ]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  postgres_data:
